import { MenuUser } from "@/domain/types/menuUser";

export const MOCK_MENU_ITEMS: MenuUser[] = [
  {
    id: 1,
    codeName: "dashboard",
    displayName: "Dashboard",
    parentId: null,
    url: "/dashboard",
    icon: "dashboard",
    orderIndex: 1,
    domainProfileId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    submenus: [],
  },
  {
    id: 2,
    codeName: "upload",
    displayName: "Upload",
    parentId: null,
    url: "/upload",
    icon: "upload_file",
    orderIndex: 2,
    domainProfileId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    submenus: [],
  },
  {
    id: 3,
    codeName: "pacientes",
    displayName: "Pacientes",
    parentId: null,
    url: "/pacientes",
    icon: "people",
    orderIndex: 3,
    domainProfileId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    submenus: [],
  },
  {
    id: 4,
    codeName: "pendencias",
    displayName: "Pendências",
    parentId: null,
    url: "/pendencias",
    icon: "error",
    orderIndex: 4,
    domainProfileId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    submenus: [],
  },
  {
    id: 5,
    codeName: "usuarios",
    displayName: "Gestão de Usuários",
    parentId: 6,
    url: "/usuarios",
    icon: "person",
    orderIndex: 1,
    domainProfileId: null,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    deletedAt: null,
    submenus: [],
  },
];
